name: CI
on: [push]
jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install pylint -r requirements.txt
      - run: python -m pylint sharif_music/*.py
  Black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - uses: psf/black@stable
  Pytype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install pytype -r requirements.txt
      - run: python -m pytype sharif_music/*.py
